name: shop_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.6
  smooth_page_indicator: ^1.0.0+2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  carousel_slider: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
